### ISSUE TITLE
Valet Cancel Button doesn't work

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#10]
admin tab > valet button

Cancel button doesn't work.  Cancel button should bring user back to admin tab screen.

![image](https://cloud.githubusercontent.com/assets/8105239/23099687/cb1215d0-f621-11e6-822a-1f0bfd8a31ca.png)

![image](https://cloud.githubusercontent.com/assets/8105239/23099689/d5d0a978-f621-11e6-8772-8e7f3250661f.png)

**Comment by Nomanghous** [comment]
@Brianklim  I have fixed this issue and its working perfectly.

**Comment by SarahGarren** [comment]
Tested and passed requirements.
