### ISSUE TITLE
Admin Tab > Fixed Loop Route - Change down button sounds

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#11]
Admin Tab > Fixed Loop Route - Change sound for the down buttons. Use "down button .mp3" in Dropbox.

![image](https://cloud.githubusercontent.com/assets/8105239/23099765/e5de4242-f623-11e6-9c80-bd92ab479324.png)

![image](https://cloud.githubusercontent.com/assets/8105239/23099767/f61d8816-f623-11e6-8645-e27626372980.png)

[down button.zip](https://github.com/IPS-Systems/SentryMobile/files/785612/down.button.zip)

**Comment by Nomanghous** [comment]
I can do this as well. Please wait project is syncing, will start working on in right now.

**Comment by Nomanghous** [comment]
@Brianklim I have fixed this issue and its working perfectly.

**Comment by SarahGarren** [comment]
Tested and passed the requirements.
