### ISSUE TITLE
Montebello-Begin Shift

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#15]
Move all the fields including the buttons up into empty space so keyboard doesn't block view of them.
![image](https://cloud.githubusercontent.com/assets/25572175/23244805/bdf5f2ea-f93c-11e6-86b0-cd1c35ba4705.png)

**Comment by Nomanghous** [comment]
@SarahGarren This issue is resolved, will commit changes soon.

**Comment by SarahGarren** [comment]
Okay for now.
