### ISSUE TITLE
Montebello-Rounds

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#16]
Currently there are two scrolling windows which is confusing for the user. Please make it one large scrolling window.
![image](https://cloud.githubusercontent.com/assets/25572175/23245189/8ea91884-f93f-11e6-9c3c-78506f9a4ab2.png)

Do not show the submit button until after 'Station Odometer' information is entered.

User should be able to see what round they are on when entering the stop information.
![image](https://cloud.githubusercontent.com/assets/25572175/23245575/602daf6c-f942-11e6-9703-81fa53f8f82b.png)

'End Time' section should not show until both fields of 'Stop 1' are complete. 

'Stop 2' fields should not show until both fields of 'Stop 1' are complete.
'Stop 3' fields should not show until both fields of 'Stop 2' are complete.
'Stop 4' fields should not show until both fields of 'Stop 3' are complete.
'Stop 5' fields should not show until both fields of 'Stop 4' are complete.
'Stop 6' fields should not show until both fields of 'Stop 5' are complete.

Station time label is incorrect, it is still showing 'End Time'.

Get rid of 'Submit Time/Odometer' button.
![image](https://cloud.githubusercontent.com/assets/25572175/23246047/bb3458fe-f945-11e6-9514-57216f96ab9e.png)

Change 'Submit' button to 'Submit Round' button.

**Comment by Nomanghous** [comment]
@SarahGarren I have added a stop button for better user experience as we cannot tell programaticaly that user has finished type. So i think Add new stop button will be better solution?

**Comment by SarahGarren** [comment]
QA passed.
