### ISSUE TITLE
Montebello - Round count

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#17]
The user must type in a total of 4 rounds only.  No more.  No less.

There is also a bug with the Round counter.
if user creates 4 rounds then submits.  then begins another shift and starts more rounds the number of rounds keeps going up.  We went up to round #9.  After Round 4, the user should not be able to create more rounds.

**Comment by Nomanghous** [comment]
@SarahGarren This issues has been resolved. Now one user can only create 4 rounds. CHECKED. Will commit changes after every bug fixed.

**Comment by SarahGarren** [comment]
QA passed.

**Comment by SarahGarren** [comment]
Using the back button the round count gets messed up.  After pressing the back button and reopening the 'Montebello Daily Log', it always starts at the begin shit which messes up the round count. Please account for user pressing the back button, back button should behave just like the 'Cancel' button and save the place and information user has imputed. 
![image](https://cloud.githubusercontent.com/assets/25572175/23336325/443da1b8-fb81-11e6-82ef-c30a28546a7d.pecloud.githubusercontent.com/assets/25572175/23336352/61d4edfc-fb82-11e6-9f15-cc8c0fa1170b.png

**Comment by SarahGarren** [comment]
Using the back button the round count gets messed up.  After pressing the back button and reopening the 'Montebello Daily Log', it always starts at the begin shit which messes up the round count. Please account for user pressing the back button, back button should behave just like the 'Cancel' button and save the place and information user has inputed. 
![image](https://cloud.githubusercontent.com/assets/25572175/23336363/00ee8754-fb83-11e6-92eb-f47769f12d40.png)

**Comment by SarahGarren** [comment]
QA passed.
