### ISSUE TITLE
Sign In / Sign Out target

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#18]
Please change the URL for sign in / out to

Account/SentryMobileSignIn
and
Account/SentryMobileSignOut

**Comment by Brianklim** [comment]
@Nomanghous are you POSTING to SentryMobileSignOut?  I'm seeing it on my side.  Please double check.  Thanks

**Comment by Nomanghous** [comment]
@Brianklim yes i am posting to Account/SentryMobileSignOut, confirmed.

**Comment by Brianklim** [comment]
@Nomanghous something isn't correct.  
First, please pass in sessionId for Account/SentryMobileSignOut.  
Second, it still seems like you're posting to Home/SentryMobileSignIn instead of Account/SentryMobileSignIn

If you go to the About Page and scroll all the way to the bottom you'll see the "home/MobileAppSignIn" url.  This is incorrect.  Do you have a sepearte URL string you're using?  This list of URLs should be dynamic and should reflect the actual URLs the app is using.

**Comment by Nomanghous** [comment]
@Brianklim I have updated all URLs dynamically but i don't know why it's still posting it to previous one. I will dig into it today and let you know about the bug.

**Comment by Nomanghous** [comment]
@Brianklim i have tested that everything on my end and it's working good. Account/SentryMobileSignOut is being posted with sessionId as well and on the about page login and signout URLs are fine.
Please check with the latest apk that i have sent and let me know if it not okay. Thanks.

**Comment by Brianklim** [comment]
cool, so dev fixed the signout missing sessionId so now it's not throwing an error.  However, I'm not seeing signout in the logs.  Sign in works correctly though.  Closing ticket.
