### ISSUE TITLE
Admin Tab > Cudahy/SF/BG/Montebello

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#19]
In the Admin Tab there are 4 buttons to enter information.  (Cudahy, SF, BG, Montebello).  I only want to show the buttons that pertain to the logged in user.  (Hide the others)

Upon sign-in, I will return "trackerSiteIds" of type List<int>.

Show the corresponding buttons if the number is in the trackerSiteIds list:
Cudahy = 22
San Fernando = 23
Bell Gardens = 21
Montebello = 24

![image](https://cloud.githubusercontent.com/assets/25572175/24786843/57935d4a-1b19-11e7-913e-bc624fc66684.png)

![image](https://cloud.githubusercontent.com/assets/25572175/24786853/659c5216-1b19-11e7-8bcc-2d4a31117d96.png)

**Comment by SarahGarren** [comment]
![image](https://cloud.githubusercontent.com/assets/25572175/24785827/c50df888-1b11-11e7-8453-bdc27dd0d334.png)

**Comment by SarahGarren** [comment]
@Nomanghous 
Please move the boxes up into the empty space.
![image](https://cloud.githubusercontent.com/assets/25572175/24941073/79155338-1efc-11e7-9fc9-1d6904010906.png)

**Comment by Nomanghous** [comment]
@SarahGarren for point (2) did you log in again after selecting the buttons?

**Comment by Brianklim** [comment]
@Nomanghous yes, I believe we tried logging in again.

**Comment by SarahGarren** [comment]
QA passed.
