### ISSUE TITLE
Map Tab - Map centering

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#2]
In the map tab, fix the centering icon.

If the user manually drags the map then turn off centering.

If centering is turned on, default to a zoomed, centered mode.

If centering is turned on and user zooms in or out, keep centered mode turned on.  Only when user drags the map off center, then turn off centering mode.  (see how app maps work)

When centering is ON, the icon should be blue. When it is OFF, the icon should be black.

The behavior described above is the same as how MAPS work in IPhone.

**Comment by SarahGarren** [comment]
on hold

**Comment by SarahGarren** [comment]
QA Passed.

![image](https://cloud.githubusercontent.com/assets/25572175/25979834/a1e29682-367f-11e7-911a-1075a61a91c0.png)
