### ISSUE TITLE
Task Tab - create functionality

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#26]
The Task Tab is a task assignment list for the driver (tablet user).  We will retrieve unassigned tasks from the server, display the unassigned tasks in the Tasks tab, and allow the driver to Accept tasks.

For testing you can use the following link to create tasks.  http://dev.ips-systems.com/Home/LoginPage?ReturnUrl=http%3a%2f%2fdev.ips-systems.com%3a80%2fsentry%2fpickuprequestkiosk

IPS07web

//Retrieve Tasks
Post to Sentry/GetTasks with parameter (string sessionId) every 5 seconds whenever user is logged in.

I will send you Json list of Ids (int), Titles (string), RiderCount (int), PickupLat (decimal), PickupLng (decimal)
[{ "Id":1, "Title":"My title", "RiderCount":1, "PickupLat":"-118.123456", "PickupLng":"33.123456" }]

//Display Tasks
Display Tasks in a pretty list.  Here is a sample of the style I'm looking for.
![image](https://cloud.githubusercontent.com/assets/8105239/23390718/b1d8a1e2-fd24-11e6-990d-2125c774a114.png)

Please please display RiderCount instead of the icon on the left of each Task.

//Accept Tasks
If the user wants to accept a task, the user has to tap on the task and slide to confirm.  

The task will be highlighted when user taps on a task.  If a task is selected then display a green slider at the bottom of the screen that reads "Slide to Accept Task".  When user slides to the right POST to Sentry/AcceptTaskAndComplete with paramters (string sessionId, int taskId).  

If "true" is returned, remove task from list, remove slider bar, and display message "Task Accepted".
If "false" is returned, display error message "Could not accept task".

![image](https://cloud.githubusercontent.com/assets/8105239/23390492/4feccc8e-fd23-11e6-9cb9-0b1967aef6cd.png)

**Comment by Nomanghous** [comment]
@Brianklim The POST Request to Sentry/GetTasks return empty response. Please confirm what's going wrong.

**Comment by SarahGarren** [comment]
QA passed with minor fixes.
