### ISSUE TITLE
Task - Select/Unselect

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#29]
When user clicks on a task to accept, an overlay should display that is a dark gray translucent teh covers the whole screen, where background is visible but it is blurry(see screenshot below). 

![image](https://cloud.githubusercontent.com/assets/25572175/23591242/37ee30f4-01a2-11e7-97bd-f255fad355c9.png)

A light green 'Slider Bar' with white words 'Slide to Accept Task' should show up on top of page that goes from darker to lighter translucent (like in the screenshot below). 

![image](https://cloud.githubusercontent.com/assets/25572175/23591585/467e8916-01a7-11e7-8151-41597be5c8b5.png)

There should be one Chevron icon, not three like it is now on the 'Slider Bar'.

![image](https://cloud.githubusercontent.com/assets/25572175/23591592/8535db64-01a7-11e7-98ae-2b7797abcbc4.png)

![image](https://cloud.githubusercontent.com/assets/25572175/23591604/a7ebf954-01a7-11e7-8da4-d4fa32c6fad2.png)

The task the user selected should show in the middle between to light blue lines(only show the task info the user selected) 

![image](https://cloud.githubusercontent.com/assets/25572175/23591443/6d9f1300-01a5-11e7-929a-668e3bc37099.png)

 The 'Cancel' button should be at the bottom  of the page centered. When user clicks it, it should go back to all the pending tasks. Should be similar to lay out I drew.

![image](https://cloud.githubusercontent.com/assets/25572175/23591491/ff4f0666-01a5-11e7-986d-6deee6c85815.png)

**Comment by SarahGarren** [comment]
@Nomanghous can you fix these please?

**Comment by Nomanghous** [comment]
@SarahGarren yes sure! i am working on it.

**Comment by SarahGarren** [comment]
QA passed with minor UI changes needed.
