### ISSUE TITLE
Task - Miscellaneous

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#32]
1- Remove the words 'Congratulations' from the Task Accepted modal. Then recenter 'Task Accepted' words, and make the font as big as 'Congratulations' was.

![image](https://cloud.githubusercontent.com/assets/25572175/23642247/012a0068-02ae-11e7-943f-c55910f5fc70.png)

2- The wording should be 'Rider Count', not 'Riders Count'.

3- Place colons after 'Task Details' (ex: "Task Details:" ) and after 'Rider Count' (ex: "Rider Count:" ). 

![image](https://cloud.githubusercontent.com/assets/25572175/23642380/1bc25a8c-02af-11e7-863c-6666e4fb4caf.png)

4- After user clicks on which task they want to accept and the page with the green slider bar comes up, I want the whole page blurred **including** the time, battery life of tablet, stopped time, and the tabs at bottom of page. This is so the user can't try to click on anything else **besides** the 'Cancel' button and slider the slider bar.

![image](https://cloud.githubusercontent.com/assets/25572175/23642600/b1255ba0-02b0-11e7-8903-31e5afca5537.png)

**Comment by Brianklim** [comment]
QA passed
