### ISSUE TITLE
Task - Start Task

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#34]
![image](https://cloud.githubusercontent.com/assets/25572175/23885436/318bb288-0830-11e7-96a0-b7b58a2cff9a.png)

1- The circle with a map is the Google Map coordinates centered on the pick up location that the driver needs to get to.  Match the blue circle to the blue for the Task Title. 

2- 'Estimated time' is the amount of time it will take the driver to arrive at the pick up location.

3- 'Estimated distance' is the distance the driver needs to go to reach the pick up location. 

4- When user clicks on the red circle with the white X, it should act like a 'Cancel' button and take user back to 'Task Tab'. Make the circle this red please #ff000097 .
![image](https://cloud.githubusercontent.com/assets/25572175/23885647/d2fdb688-0831-11e7-9e9f-31fe199f4fa6.png)

5- When user clicks on green circle with white check mark, it should act like a 'Start Task' and take user to the page with directions to pick up the passenger. Make the circle this green please #66a34cb0 .
POST Sentry/EnRouteToPickupTask with parameters (string sessionId, int taskId)
![image](https://cloud.githubusercontent.com/assets/25572175/23885705/3897996e-0832-11e7-93e6-ee54d440c428.png)

**Comment by Nomanghous** [comment]
@Brianklim From where this screen will shown up? When driver accepts the task?

**Comment by Brianklim** [comment]
The user can see this screen from 2 different ways.
1) If the user taps on an "Assigned" task from the task tab.
or
2) After the user ACCEPTS an unassigned task.

**Comment by Nomanghous** [comment]
Okay great, that's fine.

**Comment by SarahGarren** [comment]
@Nomanghous 

1- Please make full screen so user can't see the time, battery life, or anything at the top, and all the tabs at the bottom. So with the extra space now, make things bigger and easier to read. But proportional.

2- Please make the 'Cancel' and 'Submit' buttons round with the 'X' centered.

3- Make the icons on the side bigger.

4- Can we change the wording for 'Estimated Time' and 'Estimated Distance' to just 'Time' and just 'Distance'. Please and thank you.

5- Change 'Riders Count' to 'Rider count'. No 's' and no capital 'c'.

6- Can we make the area inside the details box with the 'Pick up', 'Drop off', 'Time', 'Distance', and 'Rider count' gray, it sort of looks blue right now.

7- The blue horizontal lines separating the different fields should not span the whole width of the box.

8- Can we make the field value bigger than the field label please. In my mock up I used size 9 fount for the label, and size 12 for the value. It can be different numbers, just please make the value bigger than the labels.

**Comment by SarahGarren** [comment]
@Nomanghous 

1- Please get rid of the white box that is around the map circle, make the whole background white.

2- Please move the 'Cancel' and 'Submit' button down. Then make the Details box longer and increase the size of everything inside the box.

![image](https://cloud.githubusercontent.com/assets/25572175/24229098/24807194-0f35-11e7-9223-cc74240e0312.png)

**Comment by Brianklim** [comment]
QA passed.
