### ISSUE TITLE
Task Tab - Task Display Update

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#35]
1- On the Task Tab, we need to separate the tasks into Assigned and Unassigned categories.  Please use collapsible accordions for each section.

2- When an accordion section is open it shows the tasks in that category.

3- To the left of the category titles there will be little icons (provided below). 

[
![assigned](https://cloud.githubusercontent.com/assets/8105239/23761907/57775540-04a9-11e7-9192-6d2666bf8175.png)
![unassigned](https://cloud.githubusercontent.com/assets/8105239/23761909/5790023e-04a9-11e7-88d4-0a728dd7b902.png)
](url)

![image](https://cloud.githubusercontent.com/assets/8105239/23804805/4f311de0-0570-11e7-9b1e-c9147bf436b1.png)

4- The number of tasks inside that category will go to the right of the category title inside a white pill box with black numbers.

5- To the right of the pill box, are arrows pointing down when the accordion can be expanded and pointing up when the accordion can be closed. When user has a category open already and clicks to open a different category, the category that was open before automatically closes. User can also manually close a category. If an open category causes user to not see the last category (Unassigned), then user is able to scroll down. 

6- Like in the screenshot, lets make the category that is open black, and the unopened ones a light blue with the pill box being white still. Make the background of the page white.   Category background should be gray.  Task tiles should be white as it is now. 

7- If a task is "Coming up" or "Overdue" please use the following icons:
"Overdue"
![overdue](https://cloud.githubusercontent.com/assets/8105239/23761910/57912272-04a9-11e7-876e-ca0a1f98abd4.png)

"Coming up"
![comingsoon](https://cloud.githubusercontent.com/assets/8105239/23761908/578b1116-04a9-11e7-934c-200daaec1db4.png)

Technical Information:
I will send you the following. JSON.
This is how to determine which category to place the tasks:
UNASSIGNED => If StatusId = 1
ASSIGNED => If StatusId != 1

Place icons on the task for the following cases:
COMING UP => if PickupScheduled within the next 1 hour
OVERDUE => if PickupScheduled is past current time

I'm sending you a list of the following in JSON
{
x.Id, x.StatusId, x.Title, x.RiderCount, EstimatedTime, EstimatedDistance
                    x.PickupScheduled, x.PickupLat, x.PickupLng, x.PickupNote,
                    x.DropoffScheduled, x.DropoffLat, x.DropoffLng, x.DropoffNote
}

**Comment by Brianklim** [comment]
[
![assigned](https://cloud.githubusercontent.com/assets/8105239/23761907/57775540-04a9-11e7-9192-6d2666bf8175.png)
![comingsoon](https://cloud.githubusercontent.com/assets/8105239/23761908/578b1116-04a9-11e7-934c-200daaec1db4.png)
![overdue](https://cloud.githubusercontent.com/assets/8105239/23761910/57912272-04a9-11e7-876e-ca0a1f98abd4.png)
![unassigned](https://cloud.githubusercontent.com/assets/8105239/23761909/5790023e-04a9-11e7-88d4-0a728dd7b902.png)



](url)

**Comment by Nomanghous** [comment]
@Brianklim to determine the category of the task what will i do? Is every task object in the json will have the statusId field?

**Comment by Brianklim** [comment]
@Nomanghous Yes, that is correct.  I each task will have the StatusId.  If StatusId==1 then the task goes in the Assigned category, else it goes in Unassigned category.

**Comment by Nomanghous** [comment]
@Brianklim Can you please specify the datatypes of the response as well?

**Comment by Brianklim** [comment]
Ids are int, lat/lng are decimal, rider count is int, scheduled is datetime, everything else is string

**Comment by Nomanghous** [comment]
@Brianklim great thanks, one more question. how could i add new task? http://dev.ips-systems.com/sentry/pickuprequestkiosk ? i added one using this URL and some of the fields are empty in the response.

**Comment by Brianklim** [comment]
@Nomanghous - here are some bugs I found
1) Please allow the user to tap anywhere on the task category bar to expand/contract category tasks
2) Please hide the task category if there are 0 tasks in it.  If there is only 1 category displayed, please keep it expanded.
3) Change "Pickup" to "Pick up".  Change "Dropoff" to "Drop off"
4) If value is null (i.e. "Drop off: null") please do not display "null" (i.e. "Drop off: ")
5) App Crashes when i try to expand task category.  I think app doesn't like a null.  try user IPS05/test
6) If 0 tasks, and if 1st task is "assigned", there is no sound.  It should always have a sound when a new task is received.

**Comment by Brianklim** [comment]
@Nomanghous 
1) I noticed a bug with the pick up datetime.  Even if the Task has pick up scheduled datetime = null, you are displaying a datetime.  It looks like you're using the previous task's pick up datetime.  Please make sure the values stay with the correct task.
2) Map tab is broken. Map not showing.

**Comment by SarahGarren** [comment]
@Nomanghous 

The icons are wrong. The red exclamation point is for overdue tasks. The clock is for tasks that are coming up within an hour.
![image](https://cloud.githubusercontent.com/assets/25572175/24085299/99ff2982-0cb6-11e7-823e-9c867a625562.png)

**Comment by Nomanghous** [comment]
@SarahGarren I have fixed #36 issue, will upload changes tonight.

**Comment by SarahGarren** [comment]
QA passed.
