### ISSUE TITLE
Task - Accept Task update

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#36]
NOTE: This page replaces the other 'Accept Task" page that you created.

For the Unassigned tasks, user can click on the different ones and view the details about that one they clicked on.
![image](https://cloud.githubusercontent.com/assets/25572175/23786138/2346d224-0520-11e7-92bc-3d313a7a1f47.png)

1- User will see the 'Task Title' at the top; and under in a box will be the 'Details'. Technical information: Accept Task (if task is currently unassigned) - POST Sentry/AcceptTask with parameters (string sessionId, int taskId)
The details include:
A.) 'Pick up' and 'Drop off' date and time 
B.) 'Estimated time' and 'Estimated distance'
C.) 'Rider count'

2- Icons for 'Pick up' green up arrow, 'Drop off' blue down arrow, 'Estimated time', 'Estimated distance', and 'Rider count'. Please transparent the icons.
![image](https://cloud.githubusercontent.com/assets/25572175/23783938/d1ab7354-0513-11e7-95ee-f9e7dbcc68d3.png)
![image](https://cloud.githubusercontent.com/assets/25572175/23784008/41218f8e-0514-11e7-8745-1b6ab29df7cf.png)
![image](https://cloud.githubusercontent.com/assets/25572175/23784021/55356c2a-0514-11e7-96f4-c7a21521f537.png)
![image](https://cloud.githubusercontent.com/assets/25572175/23784028/620605c2-0514-11e7-954d-da1f9af323d8.png)
![image](https://cloud.githubusercontent.com/assets/25572175/23784036/70265396-0514-11e7-9cfa-935f237f7253.png)

3- For user to accept the task, they will slide the same slider bar as the other Task Tab we created. This slider bar also says '> Slide to Accept Task'. It is still green and is a light to dark gradient. Please remember the race condition and confirm that user successfully got the task, or if another user already got the task.

4- 'Cancel' button takes user back to the first Task Tab page with the  Overdue, Coming up, Assigned, and Unassigned tabs. Cancel button will be gray with a red outline, but with a dark to light gray gradient. So at the bottom of the button it will be dark gray and as it goes up gets lighter until white. (see pictures for reference) The words 'Cancel' in black. Also please round the sides like in the picture.
![image](https://cloud.githubusercontent.com/assets/25572175/23784207/7d0f39a0-0515-11e7-9b1f-02937d92ab16.png)
![image](https://cloud.githubusercontent.com/assets/25572175/23784230/a61b3d30-0515-11e7-8ea7-5dc549dcee00.png)

5- The background will be white.
 The 'Task Title' will be blue font. (the blue is #3ab8e8 )
![image](https://cloud.githubusercontent.com/assets/25572175/23785407/70339b48-051c-11e7-9577-da1b6743368b.png)
The details box is outlined black, the individual rectangle with 'Details' will be white, and the word 'Details' will be in black. 
The rest of the box is a very light gray (the gray is #efefefff ).
![image](https://cloud.githubusercontent.com/assets/25572175/23785241/87083cbc-051b-11e7-8c52-6b0d84380e46.png)
The words 'Pick up: ', 'Drop off: ', 'Estimated time: ', 'Estimated distance: ', and 'Rider count' will be black font.
The information provided under each category will be in bigger font than the title, and will be a dark gray color. (the dark gray is #666666 ) 
![image](https://cloud.githubusercontent.com/assets/25572175/23785384/57dc1dd6-051c-11e7-9b49-16b5ad398711.png)

**Comment by Brianklim** [comment]
@Nomanghous there is a bug with this.  Please POST to the correct URL above.

**Comment by Nomanghous** [comment]
okay the URL is update and bug fixed.

**Comment by SarahGarren** [comment]
Please change the old 'Cancel' button to the new circular 'Cancel' button.

![image](https://cloud.githubusercontent.com/assets/25572175/24277782/a29e234c-0ffc-11e7-84de-066a0ed3f4ac.png)

**Comment by SarahGarren** [comment]
In ticket #52
