### ISSUE TITLE
Task - Task Picked up page

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#37]
Show this page when the user taps on a task that is already assigned to this user OR if the user presses the green 'OK' button from the start task page.  Please have the map autozoom max to keep current position and Pickup location within the screen view. 

![image](https://cloud.githubusercontent.com/assets/8105239/24031070/ac29b0de-0a9d-11e7-8117-237c0bcaec25.png)

If user taps on the top green bar show task details page like below (please animate the screen to slide):
![image](https://cloud.githubusercontent.com/assets/8105239/24031091/dcfc310a-0a9d-11e7-9953-80e35ef18403.png)

On the task details page, if user presses green '<-' button, take user back to the previous page (animate the slide).  If user presses red 'X' button, ask if the user wants to cancel task.

![image](https://cloud.githubusercontent.com/assets/8105239/24031130/1d47145a-0a9e-11e7-8d88-ef808e6b8acb.png)

If user slides green bar - POST Sentry/EnRouteToDropoffTask with parameters (string sessionId, int taskId)
If user cancels task - POST Sentry/CancelTask with parameters (string sessionId, int taskId)

New icons for 'Details' 
Notes:
![image](https://cloud.githubusercontent.com/assets/25572175/24031698/4932a98c-0aa1-11e7-9e27-e5d2a84da8ff.png)
Phone number:
![image](https://cloud.githubusercontent.com/assets/25572175/24031722/67287fe8-0aa1-11e7-997c-dccc3790d3f8.png)
Back button:
![image](https://cloud.githubusercontent.com/assets/25572175/24031739/823cad22-0aa1-11e7-82c6-c29548c0b3bb.png)

**Comment by SarahGarren** [comment]
@Nomanghous 

1- Please center the Task Title vertically as well as horizontal.

2- Also get rid of the checkerboard behind the 'Back' button.

3- When user goes from 'Pick up' page to the Details page by clicking the top chevron arrow, please make the page side from the right side of the page. Then when the user clicks the 'Back' button on the Details page, please make it slide from the left.

![image](https://cloud.githubusercontent.com/assets/25572175/24229386/5c5945fe-0f36-11e7-989a-c87e5ad320e2.png)

**Comment by SarahGarren** [comment]
@Nomanghous 

You didn't do this(#3):
When user goes from 'Pick up' page to the Details page by clicking the top chevron arrow, please make the page side from the right side of the page. Then when the user clicks the 'Back' button on the Details page, please make it slide from the left.

**Comment by SarahGarren** [comment]
QA passed.
