### ISSUE TITLE
Task - Task Dropped off page

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#38]
After user slides slider bar in the 'Pick up' page, it will take them the 'Drop off' page. 
![image](https://cloud.githubusercontent.com/assets/25572175/24031108/f1191b62-0a9d-11e7-97d0-ddea6d8a2af9.png)
1- User can tap chevron symbol in corner to take them to a 'Task Details' page. Animate screen change to slide from 'drop off' page to 'details page' 
![image](https://cloud.githubusercontent.com/assets/25572175/24031142/2cadb070-0a9e-11e7-9d7c-d23090dc88e5.png)
![image](https://cloud.githubusercontent.com/assets/25572175/24031152/3b7312d0-0a9e-11e7-8dd7-f105eb96862f.png)

2- User can tap the back arrow to take them back to 'drop off' page. Again, animate screen change to slide back to 'drop off' page from 'task deatils' page.
![image](https://cloud.githubusercontent.com/assets/25572175/24031263/e424def4-0a9e-11e7-8620-2706cbc3e1b6.png)

3- User can tap the 'cancel' button and a modal will come up. User can click 'submit' button to take them back to the 'Task Tab', and if user taps the 'cancel' button, it will take them back to the 'task details'page
If user cancels task - POST Sentry/CancelTask with parameters (string sessionId, int taskId)
![image](https://cloud.githubusercontent.com/assets/25572175/24031301/0f7f9e9a-0a9f-11e7-8e5e-b72d86faa6f5.png)
![image](https://cloud.githubusercontent.com/assets/25572175/24031313/1f1c8df4-0a9f-11e7-8579-7e25b67aa87a.png)

4- When user slides the slider bar at bottom to verify they dropped the customer off, it should go back to the 'Task Tab' page. POST to Sentry/CompletedTask(string sessionId, int taskId)

**Comment by SarahGarren** [comment]
@Nomanghous 

1- Please center the Task Title vertically as well as horizontal.

2- Also get rid of the checkerboard behind the 'Back' button.

3- When user goes from 'Drop off' page to the details page by clicking the top chevron arrow, please make the page side from the right side of the page. Then when the user clicks the 'Back' button on the Details page, please make it slide from the left.

![image](https://cloud.githubusercontent.com/assets/25572175/24229386/5c5945fe-0f36-11e7-989a-c87e5ad320e2.png)

**Comment by SarahGarren** [comment]
@Nomanghous 

You didn't do this(#3):
When user goes from 'Drop off' page to the details page by clicking the top chevron arrow, please make the page side from the right side of the page. Then when the user clicks the 'Back' button on the Details page, please make it slide from the left.

Bug I didn't get to write up:

**Comment by SarahGarren** [comment]
QA passed.
