### ISSUE TITLE
Cancel buttons

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#39]
All of these are on the admin tab.

1- 'Notify Supervisor' button. Words disappear when user starts typing. Blue outline around box. The blue is #3ab8e8ff . 'Cancel' button takes user back to Admin Tab, and the 'Submit' button submits the info and takes user back to Admin Tab.
![image](https://cloud.githubusercontent.com/assets/25572175/24536212/befcf1ee-158d-11e7-8869-bae99215ec2b.png)

2- 'New Incident' button.  Words disappear when user starts typing. Blue outline around box. The blue is #3ab8e8ff . 'Cancel' button takes user back to Admin Tab, and the 'Submit' button submits the info and takes user back to Admin Tab.
![image](https://cloud.githubusercontent.com/assets/25572175/24536224/d3b75020-158d-11e7-8adb-ca5eb942f93b.png)

3- 'Valet Request' button. 
![image](https://cloud.githubusercontent.com/assets/25572175/24536252/00bddb34-158e-11e7-9536-8111befe75fd.png)

4- 'Rename Bus' button.  Words disappear when user starts typing. Blue outline around box. The blue is #3ab8e8ff . 'Cancel' button takes user back to Admin Tab, and the 'Submit' button submits the info and takes user back to Admin Tab.
![image](https://cloud.githubusercontent.com/assets/25572175/24536285/488a4c9a-158e-11e7-9fe8-9986561d9dec.png)

**Comment by Brianklim** [comment]
@SarahGarren ticket #60 might cover one of the screenshots above.  please remove from above and use ticket #60 for that particular screen.  thanks.

**Comment by SarahGarren** [comment]
@Nomanghous 
These are the bugs I have found so far:
1- On the Admin Tab, when I click on 'Notify Supervisor' or 'New Incident', the wrong page comes up. For 'Notify Supervisor', 'New Incident' page comes up, and when 'New incident' is clicked on, 'Notify Supervisor' Page comes up. It should be Notify Supervisor with Notify Supervisor and New Incident with New incident

2- On the Valet Request page, we need to add the title 'Valet Request'.
Currently:
![image](https://cloud.githubusercontent.com/assets/25572175/24841667/28fb3742-1d3e-11e7-9286-a5476502800b.png)
Screenshot in original comment is how it should look.

3- When user types in the box for 'New Incident' and 'Notify Supervisor', the box should expand to fit all the text and so the user can see what they said above.

4- On the 'Rider Count' page, the bottom of the words 'On' and 'Off' are cut off. not sure why, simple fix. Please and thank you.
![image](https://cloud.githubusercontent.com/assets/25572175/24841719/29acce8e-1d3f-11e7-9b41-13c0ef051759.png)

**Comment by SarahGarren** [comment]
QA passed.
