### ISSUE TITLE
Cudhay/BG/SF - Begin Round or Fuel Mileage

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#45]
Cudhay- After user clicks on 'Begin Shift' it will take them to this page which gives the user the option to start a round or get fuel. 

1- If user click on 'Begin Round 1' button, it will take them to the passenger count page. This button is blue ( #42cde8ff )with a black outline.

2- The round number on the button changes depending on which round they are on.

3- If user clicks on 'Add Fuel Mileage' it will take them to the fuel mileage page. This button is green ( #8dd77dff ) with a black outline. 

4- Once the user submits a fuel mileage, the button will disappear so user can't submit another fuel mileage. Once the button is gone, please center the 'Begin Round' button.

5- The background for the whole page is white.

![image](https://cloud.githubusercontent.com/assets/25572175/24233557/448b8184-0f50-11e7-8481-4b414b8fbb47.png)
![image](https://cloud.githubusercontent.com/assets/25572175/24280060/06a6702a-100b-11e7-8811-10e3c767b1b3.png)

 Bell Gardens and San Fernando- After user clicks on 'Begin Shift' it will take them to this page which gives the user the option to start a round,  get fuel, or pick which schedule they are doing.

1- Same buttons as above (1-4). White background as well.

2- Above the buttons, will be a box that says 'Select Schedule'. When user clicks on it more boxes will pop down. Three boxes for Bell Gardens and two boxes for San Fernando. User will select a schedule and the box will close back up and where is said 'Select schedule' it now says the schedule they picked. Make the top of box a gray and the options under a lighter gray.

![image](https://cloud.githubusercontent.com/assets/25572175/24233742/6219bf12-0f51-11e7-95e6-97e914940c78.png)

![image](https://cloud.githubusercontent.com/assets/25572175/24233751/6e076a2c-0f51-11e7-8796-b7e89c2b916c.png)

**Comment by SarahGarren** [comment]
@Nomanghous 

For Bell Gardens and San Fernando, the selection box needs to say the schedule the user picked on round 1 for all the rounds.

**Comment by SarahGarren** [comment]
@Nomanghous 

1- 'Select Schedule' is showing funny on screen. Please fix. 

![image](https://cloud.githubusercontent.com/assets/25572175/24438770/987b5e56-13fe-11e7-8da2-3e5352c05f24.png)

2- User doesn't have to do 'Add Fuel Mileage' in order to end the shift. we are now going to have the 'End shift' button pop up when user is finished with all of their rounds. And if user clicks 'End Shift', it should take them to the End Shift page with the two different fields.

So if user doesn't do an 'Add Fuel Mileage', but finishes the rounds, page should look like this:
![image](https://cloud.githubusercontent.com/assets/25572175/24439052/a256c42c-1400-11e7-84ce-1d218d02e4c1.png)

If user does do 'Add Fuel Mileage' and finishes the rounds, the page should look like this:
![image](https://cloud.githubusercontent.com/assets/25572175/24439070/bfaccd32-1400-11e7-8517-f82caf11bae4.png)

**Comment by SarahGarren** [comment]
@Nomanghous 

After user finishes all the rounds, lets make the 'Select Schedule' box go away.
![image](https://cloud.githubusercontent.com/assets/25572175/24533805/d6b8fe54-157e-11e7-9af9-f0a858d0492b.png)
![image](https://cloud.githubusercontent.com/assets/25572175/24533820/e9f4e8ac-157e-11e7-88aa-04cc4135591e.png)

**Comment by Nomanghous** [comment]
@SarahGarren actually pick a schedule option was there in previous mockups that is why i did it but No problems i will fix this next built.

**Comment by SarahGarren** [comment]
QA passed.
