### ISSUE TITLE
Tasks - Alert bubble

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#46]
When a task is assigned to the user and an unassigned tasks is available it should show an alert on the Task tab when user is on a different tab. It is like the Messenger alert bubble, make the same style. If user has one assigned task, and there are 3 unassigned tasks, the bubble should have the number 4. 
![image](https://cloud.githubusercontent.com/assets/25572175/24280883/9e8a6f1c-1011-11e7-8dc1-d8833bf4bd93.png)

**Comment by Brianklim** [comment]
![image](https://cloud.githubusercontent.com/assets/8105239/24434706/1a53cc74-13e6-11e7-9e98-cf830f19b03c.png)

**Comment by Brianklim** [comment]
@Nomanghous Hi, can you please make it same style as the messages tab.  It looks like red circle with white text.

**Comment by Nomanghous** [comment]
@Brianklim yeah sure, i was about to make it white but in the mockups it was black. :) no problem i will fix this.

**Comment by Brianklim** [comment]
![image](https://cloud.githubusercontent.com/assets/8105239/24532524/0d4498a6-1576-11e7-85ba-14908af48ae1.png)
QA passed
