### ISSUE TITLE
Tasks - AcceptTaskAndComplete

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#48]
On the Accept Task page we need to add a way to "AcceptTaskAndComplete" the task.  This is to keep the same functionality for SpaceX where the driver is just notified of a pickup request and does not need directions.

For the YELLOW slider, please post to Sentry/AcceptTaskAndComplete with parameters (string sessionId, int taskId)

Design: Just like the 'Accept Task' page.

1- If 'Drop off', 'Estimated time', and 'Estimated distance' are not given, hide them.

2- If these three things are hidden, show a yellow slider bar at the bottom of the page that says 'Slide to Accept and Complete Task'. This yellow bar should look like the green one where its has a light to dark gradient. Please add that. 

3- Please make the box smaller and make everything on the page look good and not out of place. 

4- The green slider bar still takes user to the 'Start Task' page, and the cancel button still takes the user back to the 'Task Tab'. BUT the new yellow slider bar accepts the task and finishes it in one move. So once the user slides it, a new modal comes up saying 'Task Accepted and Completed', then take them back to the 'Task Tab' to begin another task.

![image](https://cloud.githubusercontent.com/assets/25572175/24945493/606718e0-1f14-11e7-84a4-1930e97ab5f4.png)

![image](https://cloud.githubusercontent.com/assets/25572175/24945747/5bf2da32-1f15-11e7-9c81-82a3f0b51b45.png)

**Comment by SarahGarren** [comment]
@Nomanghous 

When I was testing the 'Accept and Complete' button, sometimes the one I had just 'Accepted and Completed' was in the 'Unassigned' list still. It would sometimes take 4 seconds to disappear. If I clicked on the one i had 'Accepted and Completed' before, I wasnt able to slide the the 'Accept and Complete' button. 

To fix this we need to update the list quicker. Get an updated list from the sever right after the user slides the bar.

**Comment by Nomanghous** [comment]
@SarahGarren It's showing "Accept and Complete" slider only when Drop off', 'Estimated time', and 'Estimated distance' are not given. I have tested it on my side and it's working good. Please let me know if there any special case when this bug happens?

**Comment by SarahGarren** [comment]
@Nomanghous 

1- I tested this and it is not working for me. I made a task with a 'Title', 'Rider Count', 'Pick up', and 'Drop off' locations and it still showed me the page with both the 'Slide to Accept' and 'Slide to Complete'. I'm not sure what you are doing differently. 

Just to remind you; hide 'Accept and Complete' slider bar when 'Drop off' information of any kind is given, when 'Pick up' location is given, when 'Estimated time' and 'Estimated distance' is given, or any 'Notes'. 
Only show when a 'Title', Pick up' time and date, and/or 'Rider Count' are given.

2- Just a little mistake, on the end of 'Pick up notes:' there is an 'a' so it looks like 'Pick up notas:' Please get rid of the 'a'. 
![image](https://cloud.githubusercontent.com/assets/25572175/25115938/656c3a2e-23be-11e7-9b97-57b546984de0.png)

**Comment by Nomanghous** [comment]
@SarahGarren  I am going to test this one completely and let you know shortly.

**Comment by Nomanghous** [comment]
I am going to upload new apk and #48 is fixed in that. Please find that on fiverr. Thanks.

**Comment by SarahGarren** [comment]
Works well, thank you @Nomanghous

**Comment by SarahGarren** [comment]
QA Passed.
