### ISSUE TITLE
Map Tab - get shuttle positions

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#49]
Current Behavior:
The app is currently POSTING to some url every 5 seconds to get shuttle location information for the map tab.  

Expected Behavior:
Please only POST if the map tab is open.  If the map tab screen is not active please do not POST to retrieve shuttle location information.  This will reduce load on server.

Technical Note:
To get shuttle locations please POST Sentry/MobileAppGetNearbyIndividuals with parameter (string sessionId)

Testing:
@SarahGarren In order to test this, you need to setup 3 tablets. 2 tablets will use the latest 1.34 version and the other tablet with the newest apk.  Set all tablets to the same Site/Venue so they can see each other on the map tab.  Once this is setup let me know and I'll turn off the old API.  When that happens only the tablet with the new apk should see the other tablets on the map.

**Comment by SarahGarren** [comment]
@Nomanghous 

1- There is a bug and it isn't showing the shuttle position from API response.

**Comment by SarahGarren** [comment]
QA passed.
![image](https://cloud.githubusercontent.com/assets/25572175/25264196/2d9fcb52-261a-11e7-92aa-fb5f562e84f1.png)
