### ISSUE TITLE
ENH: Update Admin Tab buttons

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#5]
We need to display the buttons nicely so users can find what they need quickly.  Each category is by color and section.  Please match the colors and icons as closely as possible.
![image](https://cloud.githubusercontent.com/assets/8105239/22630423/c528fca6-ebae-11e6-90ae-6c1d7032f9c4.png)

**Comment by SarahGarren** [comment]
Complete.
