### ISSUE TITLE
Task - cancel button & icons

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#52]
1- Please change the old 'Cancel' button to the new circular 'Cancel' button.

![image](https://cloud.githubusercontent.com/assets/25572175/24277782/a29e234c-0ffc-11e7-84de-066a0ed3f4ac.png)

2- The 'Overdue' icon is not showing up sometimes. Please fix this. 

![image](https://cloud.githubusercontent.com/assets/25572175/24436722/08a05644-13f2-11e7-8866-218d66b2b4cf.png)

**Comment by Brianklim** [comment]
![image](https://cloud.githubusercontent.com/assets/8105239/24532620/b0881dbc-1576-11e7-924f-5042e97c2132.png)

QA passed.... kinda.  Icons should refresh automatically, but currently the user has to manually refresh the screen for the icons to update.
