### ISSUE TITLE
Cudahy/BG/SF - Begin and End shift update

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#53]
There was miscommunication between Brian and I, and so I didn't know there had to be fields to fill out when beginning and ending a shift. So sorry and hope this isn't to much of a hassle, similar to the end and begin shift in 1.33.

BEGIN SHIFT- 

1- When user selects 'Begin shift' this page will open. When the page opens, make sure the Android keyboard is up. 

2- User needs to fill out four different fields. 'Driver', 'Bus name', 'Start miles yard', and 'In service miles'.

3- For 'Driver:', and 'Bus name:' the Android keyboard needs to show. And for 'Start miles yard:' and 'In service miles:' the Android number pad needs to show.

4- The 'Cancel button takes user back to the 'Admin Tab', and the submit button takes user to the page with 'Begin Round' and 'Add Fuel mileage'.

![image](https://cloud.githubusercontent.com/assets/25572175/24438303/4986de72-13fb-11e7-849c-dc0110e2c2ba.png)

This is what the old one looked like.

![image](https://cloud.githubusercontent.com/assets/25572175/24439414/f626436e-1402-11e7-903d-2a662d36acd4.png)

END SHIFT-

1- When user selects 'End shift' this page will open. When the page opens, make sure the Android number pad is up.

2- User needs to fill out two different fields. 'Out of service miles:', and 'End miles yard:'.

3- For 'Out of service miles:' and 'End miles yard:' the Android number pad needs to show.

4- The 'Cancel' button takes user back to page with only 'Add Fuel Mileage' showing, if they didn't already add one, and with the 'End Shift' button. The 'Submit' button takes user back to 'Admin Tab'.

![image](https://cloud.githubusercontent.com/assets/25572175/24438665/afede5a0-13fd-11e7-81d2-2ad44612a069.png)

This is what the old one looked like.

![image](https://cloud.githubusercontent.com/assets/25572175/24439452/27f40408-1403-11e7-9ccd-82fc0072e186.png)

**Comment by SarahGarren** [comment]
1- For Cudahy Daily Log, after I enter Begin Shift information, submit it, it takes me straight to 'End Shift', or the app crashes when I try to begin a round or add fuel mileage. It needs to work just the like other two logs, please fix.

2- If app does crash, and user opens the app again, it needs to remember where they were. If a user is on round 4, app crashes, they reopen it, and go back to 'Cudahy Daily Log', it needs to open to the page with the option of 'Begin Round 4' or 'Add Fuel Mileage'. This is so the user doesn't have to enter the information again.

3- San Fernando, and Bell Gardens-
When I enter all of the information and submit the End Shift information it does not save to database. They need to save.

**Comment by Nomanghous** [comment]
@SarahGarren on my sending the API is responding with "true" when i end any shift. I don't know if it's still not posting correctly. Please let me know if you are still facing this issue, Thanks.

**Comment by SarahGarren** [comment]
@Nomanghous 

When the app is first installed, Bell Gardens and San Fernando round save. Perfect! After an install and I complete a round for Cudahy, it sometimes does not save the begin shift information. Please try to figure out what is going wrong and fix it. Again, it only happens once in a while but is a big problem.

**Comment by Nomanghous** [comment]
@SarahGarren okay i will have a look at it and let you know how it goes on my side.

**Comment by Nomanghous** [comment]
![capture](https://cloud.githubusercontent.com/assets/12783763/24700739/864617f8-1a11-11e7-8ecf-83004fca2ef3.PNG)
You can see the parameters with which i am posting to the following url.
URL: http://dev.ips-systems.com/Sentry/StartShift
API is response is "false" even when i tried with other Bell Gardens and San Fernando. 
Please let me know how do i know that when start shift is successfully posted.

**Comment by Brianklim** [comment]
when you POST to StartShift or EndShift I will return true if successfully saved the information.  If you don't get a true response back, then notify the user the information wasn't saved and allow them to submit again.

**Comment by Nomanghous** [comment]
okay actually i have tried several times to start a shift and it's returning false every time. It's posting perfectly from my side, every parameter has a value. I don't know if there is some kind on foreign key on driver names or bus names from any parent table? that these must be present in the present table while starting the shift. Please confirm.

**Comment by SarahGarren** [comment]
QA passed.
