### ISSUE TITLE
Tasks - Design updates

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#56]
1. A- On the '**Accept Task**', '**Pick Up**', and **'Drop Off**' pages, please fix the blue lines so they do not span the entire width of the Details Box.
Currently-
![image](https://cloud.githubusercontent.com/assets/25572175/24537003/d90a0efe-1593-11e7-8ac4-3a7b8d52e186.png)
 Should be- 
![image](https://cloud.githubusercontent.com/assets/25572175/24537018/fd25e7c2-1593-11e7-8445-938ba50c9185.png)

2- When user is typing information in a box on 'Begin Shift', Pax Count', 'Add Fuel Mileage', and 'End Shift' pages, the box needs to have a blue outline. And when the page is first opened, no boxes will have an outline until they click on a box. When user taps on a different box, the outline needs to change to that one. 
![image](https://cloud.githubusercontent.com/assets/25572175/24537261/d8368b72-1595-11e7-8d2d-82ca99132b1e.png)
![image](https://cloud.githubusercontent.com/assets/25572175/24537276/e636ca52-1595-11e7-8e2b-045b7e43061b.png)
![image](https://cloud.githubusercontent.com/assets/25572175/24537281/ee8fc3de-1595-11e7-9263-35dc913fb4bc.png)

3- Please get rid of the black line around the map on the 'Start Task' page.
![image](https://cloud.githubusercontent.com/assets/25572175/24942494/3a57aa56-1f06-11e7-9ba6-39d2189b25ac.png)

4- The end of the route should not go below the red dashed line I drew. So if it is bigger please zoom out a little so user can see the full picture without anything hidden or in a small space. 
![image](https://cloud.githubusercontent.com/assets/25572175/24942849/6c79127a-1f08-11e7-9ba9-9a64132d1bfc.png)

5- Pleasse make the arrows bigger for 'Pick up' and 'Drop off'. And Increase the Title font. 
Accept Task page-
![image](https://cloud.githubusercontent.com/assets/25572175/25035808/b1ffd872-20a4-11e7-9e8e-0e02768c60a1.png)
Start Task page-
![image](https://cloud.githubusercontent.com/assets/25572175/25035836/e9466b16-20a4-11e7-9485-8dfaab551309.png)
Details page-
![image](https://cloud.githubusercontent.com/assets/25572175/25035545/1297df56-20a3-11e7-889a-85eaa2ac3598.png)

**Comment by SarahGarren** [comment]
@Nomanghous 

When I click on an assigned task, it takes me to the page below.

![image](https://cloud.githubusercontent.com/assets/25572175/25115396/dfe4601e-23ba-11e7-952f-131624c3d982.png)

It should not do this. When user clicks on an assigned task, it should take them to the 'Start Task' page. 

Then when I try to click the 'Cancel' button, it doesn't work. And the 'Back' button causes the screen to turn white and seems like it restarts the app and takes me to the 'Route Tab'. It should not do this. Please fix this. 

Because of this bug I am not able to test much, but please make sure before sending a new akp that it hits all the requirements I made.

**Comment by Nomanghous** [comment]
@SarahGarren yes sure, because of work load i couldn't able to test it. My QA will be in charge from Monday and after that he will make sure that everything works well before i submit any work.

**Comment by SarahGarren** [comment]
@Nomanghous sounds good, thank you. And just to let you know, I did just update the comments so make sure you didn't miss anything.

**Comment by SarahGarren** [comment]
![image](https://cloud.githubusercontent.com/assets/25572175/25116587/8cde4224-23c2-11e7-9bcf-8508ae50a6bb.png)

2- 
![image](https://cloud.githubusercontent.com/assets/25572175/25116767/a2958f68-23c3-11e7-9643-4cb1e4eaeeb7.png)

**Comment by Nomanghous** [comment]
These are fixed in the latest apk. Please test that one. I have sent on fiverr.

**Comment by SarahGarren** [comment]
@Nomanghous 

1- When the map page comes up for 'Drop off' or 'Pick up', the map is zoomed out to much.

![image](https://cloud.githubusercontent.com/assets/25572175/25262915/7bdcedb8-2610-11e7-8497-7229e8267254.png)

2- When there is no 'Drop off Location', make the page open to users current position zoomed in and centered.
![image](https://cloud.githubusercontent.com/assets/25572175/25264061/1ee49620-2619-11e7-93d0-1e486ed8d1b0.png)

**Comment by SarahGarren** [comment]
@---------

1- The Rider Count 'Cancel' button is not working. Please fix this so when user clicks on it, it takes them back to the Admin Tab.

2-

**Comment by SarahGarren** [comment]
@Nomanghous 
I found a bug that has just come up with the Rider Count page.

Steps to recreate: Open 'Rider Count' on the Admin Tab, submit some numbers, and reopen 'Rider Count' the numbers don't appear and it looks messed up.

Please fix this.

![image](https://cloud.githubusercontent.com/assets/25572175/25319217/118d9ace-2850-11e7-83eb-d0f443a6cbaf.png)

**Comment by Brianklim** [comment]
Looks good.  QA passed.
