### ISSUE TITLE
Login Settings

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#59]
In the login page, lets remove the login settings page (the page where we set the app environment)

Instead, let's specify the environment using the username field.  For example, if I want to run the app in the dev environment, then I'll type dev::< username > into the username field.  If I want to run the app in qa then i'll type qa::< username >.  If I want production then I'll type <username> into the username field. ("<username>" is whatever username we want to log in with)

Please remove the settings icon (bottom left of login page) and remove the settings page.  we will not use this any more.

![image](https://cloud.githubusercontent.com/assets/25572175/24786649/f99367ae-1b17-11e7-877c-93a3dc146bf4.png)

![image](https://cloud.githubusercontent.com/assets/25572175/24786622/c73d4676-1b17-11e7-95d1-3ae153bf9842.png)

**Comment by SarahGarren** [comment]
![image](https://cloud.githubusercontent.com/assets/25572175/24786624/cad58d70-1b17-11e7-9ed4-03f302b8413f.png)

![image](https://cloud.githubusercontent.com/assets/25572175/24786622/c73d4676-1b17-11e7-95d1-3ae153bf9842.png)

**Comment by SarahGarren** [comment]
![image](https://cloud.githubusercontent.com/assets/25572175/24786649/f99367ae-1b17-11e7-877c-93a3dc146bf4.png)


![image](https://cloud.githubusercontent.com/assets/25572175/24786622/c73d4676-1b17-11e7-95d1-3ae153bf9842.png)

**Comment by SarahGarren** [comment]
@Nomanghous 

When a user logs out, please remember the exact username they had entered before. Right now it remembers 'ips03' but I logged in as 'dev::ips03'. so please make this so it remembers 'dev::ips03' or which ever username the user uses.
![image](https://cloud.githubusercontent.com/assets/25572175/24941398/f9a0c56c-1efe-11e7-9f02-48210bf56e0c.png)

**Comment by Brianklim** [comment]
QA passed
