### ISSUE TITLE
Pause / Resume tracking button

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#6]
Remove the pause/resume button from the map tab page.  Create a new button in the Admin tab and add it to the correct section.  See screenshot.

When the user clicks on the Pause Tracking button a popup should appear with a resume button.  User can't do anything to the app until they press "resume".  Pressing resume closes the window and allows user to use the app.

Note, please make sure that if the user is PAUSE they can't do anything to the app.  Even if they close the app and open again.  It should show the popup screen until they hit "resume".

When this is pressed post to Sentry/SetPauseResumeSentryTrackerTracking with parameter (string sessionId, bool setPause)

Picture is just a mock up. So fix the text alignment so it looks good.

![image](https://cloud.githubusercontent.com/assets/8105239/22630430/e316529a-ebae-11e6-8149-8ecc25fde06e.png)
![image](https://cloud.githubusercontent.com/assets/8105239/22630444/fda16b36-ebae-11e6-8309-edbef24ce5c1.png)

**Comment by SarahGarren** [comment]
There is a bug. Pausing and resuming tracking is not posting data to the server.

**Comment by Brianklim** [comment]
QA passed
