### ISSUE TITLE
Admin Tab > Rider Count

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#60]
change this page to the up-tick and down-tick counter

We need two numbers.  
1) number of passengers on
2) number of passengers off

![image](https://cloud.githubusercontent.com/assets/25572175/24787092/1e1efb76-1b1b-11e7-9752-aa37c65ef91d.png)

**Comment by SarahGarren** [comment]
![image](https://cloud.githubusercontent.com/assets/25572175/24787092/1e1efb76-1b1b-11e7-9752-aa37c65ef91d.png)

**Comment by SarahGarren** [comment]
@Nomanghous 

Simple fix on this page.

On the 'Rider Count' page, the bottom of the words 'On' and 'Off' are cut off. not sure why, simple fix. Please and thank you.
![image](https://cloud.githubusercontent.com/assets/25572175/24841719/29acce8e-1d3f-11e7-9b41-13c0ef051759.png)

**Comment by SarahGarren** [comment]
@Nomanghous 
fix this
![image](https://cloud.githubusercontent.com/assets/25572175/24941046/35b1b3ca-1efc-11e7-87e6-a3b3036a516f.png)

**Comment by Brianklim** [comment]
QA passed
