### ISSUE TITLE
GPS turn-by-turn navigation

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#64]
I want to add turn-by-turn navigation to help the driver get to pickup location and also to get to dropoff location.

Please come up with a way to do this.  Keep in mind the driver still needs to swipe to confirm pickup and swipe to confirm dropoff.

I found this like that might help with one possible solution. http://stackoverflow.com/questions/24531391/is-it-possible-to-create-turn-by-turn-gps-navigation-app-on-android-using-google

Turn-by-turn directions to both pick up and drop off locations.

![image](https://cloud.githubusercontent.com/assets/25572175/25648094/f5af5c78-2f7c-11e7-8474-3ead7f3adee6.png)

![image](https://cloud.githubusercontent.com/assets/25572175/25648098/006bf900-2f7d-11e7-9b18-bffe5cc9f42c.png)

**Comment by Brianklim** [comment]
QA passed
