### ISSUE TITLE
Back Arrows

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#66]
We need to start making buttons work the same as others.

1- When user is on any Tab (Routes, Maps, Tasks, Messages, or Admin) the back arrows at the bottom of the screen should not do anything when they are pushed. so Please disable all the back arrows when on this page. 

2- On the Admin Tab, when' Notify Supervisor', 'New Incident', 'Rider Count', 'Valet Request', and 'Rename Bus' buttons are tapped and the page to in put information comes up, the back arrows at the bottom of the screen should be disabled. The only way the user can go back to the previous page is to click our 'Cancel' button.

3- Message Tab>private conversation. This back button should be disabled as well.

4- The 'Bell Gardens, 'Cudahy', 'Montebello', and 'San Fernando' Daily Logs, all of their back buttons need to be disabled. 

5- Task Tab>any task. All of the back buttons needs to be disabled. Starting with the 'Accept Task' page to the 'Drop off' page.

6- About>please disable the back button here too.

This button

![image](https://cloud.githubusercontent.com/assets/25572175/25558608/149bfd76-2cdf-11e7-954c-407ad8c960c1.png)

**Comment by jubayer23** [comment]
Ma be i dont have the access of  The 'Bell Gardens, 'Cudahy', 'Montebello', and 'San Fernando' Daily Logs. Please check

**Comment by SarahGarren** [comment]
@jubayer23 I gave you access to these. Log into IPS07. Username: dev::ips07  Password: test

**Comment by jubayer23** [comment]
Can you please tell me how to test Message Tab>private conversation??

**Comment by Brianklim** [comment]
@jubayer23 I sent messages from IPS03 and IPS04 in dev.  Please log in to tablet and take a look. Thanks

**Comment by SarahGarren** [comment]
QA passed.
