### ISSUE TITLE
Message Conversation - Display Source

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#68]
Problem: Conversation source is not always showing depending on whether the user taps on received message or sent message on Messages tab.

Expected Behavior: As a tablet user, I want to see who I'm talking to in the message conversation.

Solution: If I tap on a received message in the messages tab, you need to display the FROM USER information at the top of the conversation page.  If I tap on the sent message in the messages tab, you need to display the TO USER information at the top of the conversation page.

![image](https://cloud.githubusercontent.com/assets/25572175/25512825/713cde70-2b85-11e7-9363-e72edeae913e.png)

**Comment by Nomanghous** [comment]
@Brianklim If I tap on the sent message in the messages tab, you need to display the TO USER information at the top of the conversation page. I am not getting TO USER Information in message object. ?

**Comment by SarahGarren** [comment]
@Nomanghous 

You are sending userA ID and userB ID as the same thing. This is the reason why the conversation doesn't work. You are sending in the same userID.

![image](https://cloud.githubusercontent.com/assets/25572175/25646442/4d024f4a-2f6d-11e7-8e50-db08bb0fa86e.png)

**Comment by Brianklim** [comment]
QA passed
