### ISSUE TITLE
Message Conversation - Date bug

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#69]
When a message conversation is opened, the dates they were sent are wrong. Test-test5 were all sent today but it is saying they were sent on the 25th of April. This happens when I open a conversation, send a message to another tablet, go back to Message Tab, then back into the conversation. It only says the most recent message was sent today. Please fix it so the dates are the correct days they were sent.
![image](https://cloud.githubusercontent.com/assets/25572175/25513318/2ba4570e-2b89-11e7-9bbb-708f47efdf02.png)

**Comment by SarahGarren** [comment]
@Nomanghous 

On the Message Tab, the sent time is correct. When I go into the private messages the sent time is incorrect. Please fix. Be careful not to mess up the sent date when fixing this.

![image](https://cloud.githubusercontent.com/assets/25572175/25646545/4c0d2258-2f6e-11e7-8d67-7947a1c85061.png)

![image](https://cloud.githubusercontent.com/assets/25572175/25646565/8e31d656-2f6e-11e7-95aa-1978613b84ac.png)

**Comment by Brianklim** [comment]
QA passed
