### ISSUE TITLE
Replace Valet Tab

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#7]
Replace the valet tab with a tab called "Tasks".

Use this icon http://www.freeiconspng.com/uploads/tasks-icon-15.png

Create a new Valet Button in Admin Tab called "Valet Request" and make button green and place next to "Rider Count" button.  Use this icon https://cdn4.iconfinder.com/data/icons/hotel-facilities-2/512/valet-parking-512.png

**Comment by Brianklim** [comment]
if the user presses cancel, please return user back to the Admin Tab

**Comment by SarahGarren** [comment]
There is a bug but written up on issue #6.

**Comment by SarahGarren** [comment]
There is a bug but written up on issue #6.
