### ISSUE TITLE
Disable Messages/Tasks Tab

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#72]
When user logs in (SentryMobileSignIn) I will send you two new values in the response. "enableTasksTab" and "enableMessagesTab".

If "enableTasksTab" is true, allow user to use Tasks Tab and also check for tasks using API.  If false, then disable Tasks Tab (make tab look disabled) and do not check API for tasks.

If "enableMessagesTab" is true, allow user to use Messages Tab and check API for new messages.  If false, disable Messages Tab and no not check API for messages.

**Comment by Brianklim** [comment]
@SarahGarren Can you create a mock-up for what the disabled tabs should look like.

**Comment by Brianklim** [comment]
@Nomanghous 
Everything looks good except 1 bug.

Current Behavior:
Currently, you are hitting GetUnreadMessages every 5 seconds no matter if messages tab is enabled or disabled.

Expected behavior:
Do not call GetUnreadMessages if messages tab is disabled.  Only call it if messages tab is enabled.

**Comment by Nomanghous** [comment]
@Brianklim okay i will fix that and send you apk in 30 minutes.

**Comment by Brianklim** [comment]
QA passed. 1.35q.apk
