### ISSUE TITLE
Login Error Message Missing

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#74]
If user types in a wrong password or wrong username or tries to log in using a user that is not a mobile app user (ips03web) the server returns status = false and an error message in the response.

This error message needs to be displayed so the user is informed why the app is not logging them in.

Please display the response message from the server if log in failed.

To get rid of the modal, user can tap anywhere on the screen.  We have used this modal in the past.  Please reuse code if you can.

![image](https://cloud.githubusercontent.com/assets/25572175/25559531/2ef2753a-2cf1-11e7-9830-abd7cfc81997.png)

**Comment by SarahGarren** [comment]
@jubayer23 

Everything looks good, but please make it so if user clicks **anywhere** on the screen the error message goes away.

**Comment by Brianklim** [comment]
![image](https://cloud.githubusercontent.com/assets/8105239/26164924/13edc712-3ae3-11e7-93d0-5dee5ed86d14.png)
QA passed
