### ISSUE TITLE
Keyboards - Admin Tab

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#75]
Admin Tab>'Notify Supervisor', 'New incident', 'Rider Count', 'Valet Request', and 'Rename Bus' when the user taps any of these buttons, the keyboard should automatically be up when the page opens, but they shouldn't be able to hid the keyboard. So please disable the down arrow at the bottom of the screen. 

Please Disable this button

![image](https://cloud.githubusercontent.com/assets/25572175/25558495/d04887cc-2cdc-11e7-9724-4eb7d80049d3.png)

**Comment by jubayer23** [comment]
in 'Rider Count', 'Valet Request i don't find any keyboard input filed where keyboard need to show up.

**Comment by Brianklim** [comment]
okay, if the keyboard never shows that's fine too.  thanks.

**Comment by SarahGarren** [comment]
QA passed.
