### ISSUE TITLE
Rename Bus Update

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/SentryMobile#80]
Because of the cursor on this page, it looks like if the user were to start typing, they would type in the middle of 'Rename Bus'. To get rid of this problem, we are going to move the title 'Rename Bus' up so the text box just had the cursor in it.

![image](https://cloud.githubusercontent.com/assets/25572175/25558761/43e363be-2ce2-11e7-8e77-498aef7afb19.png)

**Comment by Brianklim** [comment]
@jubayer23  The UI looks great, however, when I submit the form the app crashes.  Please fix.

**Comment by SarahGarren** [comment]
QA Passed.

**Comment by SarahGarren** [comment]
QA Passed.
