### ISSUE TITLE
Montebello Daily Log

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#9]
add new button in Admin Tab called "Montebello Daily Log".  this button should be in a new section with new color under (red) section.  Please modify icon http://v-count.com/wp-content/uploads/2014/12/icon-team.png to match existing style icons.

When user presses "Montebello Daily Log" button display full page with "Begin Shift" button:
![image](https://cloud.githubusercontent.com/assets/8105239/23106882/1281dbda-f6a9-11e6-904f-61c38b02599c.png)

When user presses Begin Shift button display the following fields:
"Date"  (datetime)
"Vehicle"  (string)
"Driver" (string)
"Route" (string)
"Start Odometer" (decimal)
Cancel button
Submit button
![image](https://cloud.githubusercontent.com/assets/8105239/23106910/71d075ec-f6a9-11e6-9dec-18974c491d70.png)

After user presses Submit button display Round #1 page:
"Start Time" (datetime)
"Start Odometer" (decimal)

Stop #1 - Stop #6 
"Distance" (decimal)
"Pax Count" (int)

"End Time" (datetime)
"End Odometer" (decimal)

"Station Time" (datetime)
"Station Odometer" (decimal)

![image](https://cloud.githubusercontent.com/assets/8105239/23106939/cfcb8fb0-f6a9-11e6-8be8-bbae7302c1c7.png)
![image](https://cloud.githubusercontent.com/assets/8105239/23106948/ed1a040c-f6a9-11e6-8ceb-fad40e0e7cd7.png)

The user must type in Start Time and Start Odometer.  Once completed, Stop #1 (Distance and Pax Count) should be displayed.  When Stop #1 fields are complete Stop #2 fields should be displayed so the user can type in data.  etc... (Max 6 stops.  Min 1 stop.)

Once user types in atleast 1 stop (Distance + Pax Count), then "End Time" and "End Odometer" fields should be displayed.

Once "End Time" and "End Odometer" fields are complete "Station Time" and "Station Odometer" fields should be displayed.

Once "Station Time" and "Station Odometer" fields are complete, the user can Submit this Round.

![image](https://cloud.githubusercontent.com/assets/8105239/23107032/00ef95cc-f6ab-11e6-8652-58d53b7bfef0.png)

======================
User must enter a total of 4 rounds.

Once 4 rounds are complete, show screen similar to the Begin Shift screen, but called it "End Shift".  When the user presses "End Shift" display a single decimal field called "End Odometer" (decimal) and Cancel and Submit button.

When the user presses the Submit button Submit (posts data to Custom/SaveMontebello(string sessionId, string json).  see below for the model.  send me json that can be deserialized into the below model.)

![2017-02-08 08 53 20](https://cloud.githubusercontent.com/assets/8105239/22848600/8e3bfef0-efaa-11e6-92b9-ba6b1daf63cb.jpg)

![image](https://cloud.githubusercontent.com/assets/8105239/22851543/30b87134-efda-11e6-8134-63a4cd634c82.png)

**Comment by SarahGarren** [comment]
Writing separate bug tickets.
